### PR TITLE
Add -t option to nvidia-detect for terse output (package name only).

### PR DESCRIPTION
**Pull request by misterbonnie**
This makes it possible to do, for example:

$ yum install $(nvidia-detect)

### CODE REVIEW

**Comment by pjperry** [comment]
$ yum install $(nvidia-detect -t)

Nice, great suggestion.

I'm almost tempted to make the terse output (package name only) the default output and add a verbose (-v) switch for regular output.

Errors / warnings could probably still be printed by default as you would presumably want yum install $(nvidia-detect) to fail when nvidia-detect returns warnings.

**Comment by jcpunk** [comment]
Looks awesome!

Two relatively minor points, should your "README" example have a '-t' on it?

In "nvidia-detect.c" I think there may be a typo in line 114.

**Comment by pjperry** [comment]
Merged, and fixed typo mentioned above - many thanks.

I'm going to start a discussion thread on the elrepo mailing list with a view to making this the default behaviour and using a verbose flag (-v) to provide the current more verbose output.

**Comment by pjperry** [comment]
Discussion thread here:

http://lists.elrepo.org/pipermail/elrepo/2015-February/002547.html

**Pull request merged**
