### PR TITLE
Renamed selinux package for bumblebee to bumblebee-selinux

### PR DESCRIPTION
**Pull request by HellboyRob**

### CODE REVIEW

**Comment by toracat** [comment]
Rob, 
Should we go ahead and build/release bumblebee and bbswitch using the current code?

**Comment by HellboyRob** [comment]
Yes. It run those versions on my laptop.
The selinux policy takes care of the loading handeling acpi calls.

Akemi Yagi <notifications@github.com> schreef op 6 april 2015 20:05:53 CEST:
>Rob, 
>Should we go ahead and build/release bumblebee and bbswitch using the
>current code? 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/elrepo/packages/pull/112#issuecomment-90178020

-- 
Sent from my Phone

**Comment by toracat** [comment]
Hi Rob,

I have built  bumblebee, bumblebee-selinux, and bbswitch and released them to the elrepo-testing repo. They will sync to our mirrors shortly. Could you test them please? If they are OK, I'll move them to the main repo.

Thanks,
Akemi

**Comment by HellboyRob** [comment]
Hi Akemi,

I installed the packages, looks good to me.

Regards,

Rob

**Comment by toracat** [comment]
Thanks, Rob, for checking. I've moved them to the main repo. Will send out
an announcement shortly.

Akemi

**Comment by HellboyRob** [comment]
Thanks

Akemi Yagi <notifications@github.com> schreef op 7 april 2015 18:31:51 CEST:
>Thanks, Rob, for checking. I've moved them to the main repo. Will send
>out
>an announcement shortly.
>
>Akemi
>
>On Tue, Apr 7, 2015 at 9:25 AM, HellboyRob <notifications@github.com>
>wrote:
>
>> Hi Akemi,
>>
>> I installed the packages, looks good to me.
>>
>> Regards,
>>
>> Rob
>>
>> On 04/07/2015 08:01 AM, Akemi Yagi wrote:
>> >
>> > Hi Rob,
>> >
>> > I have built bumblebee, bumblebee-selinux, and bbswitch and
>released
>> > them to the elrepo-testing repo. They will sync to our mirrors
>> > shortly. Could you test them please? If they are OK, I'll move them
>to
>> > the main repo.
>> >
>> > Thanks,
>> > Akemi
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> >
><https://github.com/elrepo/packages/pull/112#issuecomment-90377990>.
>>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/elrepo/packages/pull/112#issuecomment-90631812>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/elrepo/packages/pull/112#issuecomment-90635531

-- 
Sent from my Phone

**Pull request merged**
