### PR TITLE
Create new package with custom selinux policy for bumblebee

### PR DESCRIPTION
**Pull request by HellboyRob**
Created a custom selinux policy for bumblebee, so it can interact with bbswitch.
It's a seperate package, so easier to maintain.

### CODE REVIEW

**Comment by pjperry** [comment]
I have no idea if this is the correct way to handle packaging of selinux policy so I'm unable to offer review, but I'll merge it and invite others to comment.

**Comment by toracat** [comment]
I am going to ask the SELinux guy, Dan Walsh, for his advice.

**Comment by HellboyRob** [comment]
It's from fedora packaging guide.

Akemi Yagi <notifications@github.com> schreef op 4 april 2015 16:59:20 CEST:
>I am going to ask the SELinux guy, Dan Walsh, for his advice.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/elrepo/packages/pull/111#issuecomment-89590810

-- 
Sent from my Phone

**Comment by wolfy67** [comment]
On 4 aprilie 2015 18:11:06 EEST, HellboyRob <notifications@github.com> wrote:
>It's from fedora packaging guide.
>
Can you please point to the exact paragraph or wiki page ? I do not remember this part of the guide and searching using my phone as terminal is a bit difficult



>Akemi Yagi <notifications@github.com> schreef op 4 april 2015 16:59:20
>CEST:
>>I am going to ask the SELinux guy, Dan Walsh, for his advice.

**Comment by HellboyRob** [comment]
https://fedoraproject.org/wiki/SELinux_Policy_Modules_Packaging_Draft

wolfy67 <notifications@github.com> schreef op 4 april 2015 17:31:56 CEST:
>On 4 aprilie 2015 18:11:06 EEST, HellboyRob <notifications@github.com>
>wrote:
>>It's from fedora packaging guide.
>>
>Can you please point to the exact paragraph or wiki page ? I do not
>remember this part of the guide and searching using my phone as
>terminal is a bit difficult
>
>
>
>>Akemi Yagi <notifications@github.com> schreef op 4 april 2015 16:59:20
>>CEST:
>>>I am going to ask the SELinux guy, Dan Walsh, for his advice.
>
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/elrepo/packages/pull/111#issuecomment-89598107

-- 
Sent from my Phone

**Comment by toracat** [comment]
Yes, the referenced article describes use of a subpackage. I am fine with this method. The only thing is that they suggest the naming of 'myapp-selinux' (rather than selinux-myapp). Not a critical issue but this naming will better indicate that this package belongs to 'myapp'.  Rob, would you mind renaming yours?

**Comment by HellboyRob** [comment]
Hi,

I changed the name of the package to bumblebee-selinux.

Regards,

Rob

**Comment by toracat** [comment]
Thanks. I've merged it.

**Comment by HellboyRob** [comment]
Thanks. 

Akemi Yagi <notifications@github.com> schreef op 6 april 2015 18:58:06 CEST:
>Thanks. I've merged it.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/elrepo/packages/pull/111#issuecomment-90155652

-- 
Sent from my Phone

**Pull request merged**
